[package]
name = "wgsl_toy"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = "0.29.10"
env_logger = "0.10"
log = "0.4"
wgpu = "^0.19"
bytemuck = { version = "1.12", features = [ "derive" ] }
pollster = "0.3.0"
glam = { version = "0.24.2", features = [ "bytemuck" ] }
